### ISSUE TITLE
Create shared js file

### ISSUE THREAD

**Issue by Enngage** [CollierCZ/plain-javascript-tutorial#5]
How about if you created a shared 'core.js' file where you defined your delivery client, app and other shared code?

**Comment by CollierCZ** [comment]
This would require modules, which would require running the files through a local web server. While that's realistically easy enough, I wanted the app to be so simple as to not require anything other than the files. I can add a note to the tutorial about it applying for larger projects.

**Comment by Enngage** [comment]
@CollierCZ You can create the `core.js` and link it on your html pages `before` your other script files. You could initialize client, classes, app or other stuff there and store in a global var or you could think of it as a class which only provides functions, but does nothing at all on its own. For example, you could have a method there such as:

```javascript
function getDeliveryClient()
```

which you would call on your other script pages. And similarly you could have other 'helper' methods for other stuff (handling errors, adding elements to DOM ..)

The goal would be to avoid **code duplications**.

**Comment by CollierCZ** [comment]
Yes, of course. I was overcomplicating things. It's really much simpler. Thanks for sticking with my stupidity. Will get on it.
